apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: registry.gitlab.com/mattia.gisiger/347/chat:latest
        ports:
        - containerPort: 3000